version: "3"

services:
  question_doc_converter:
    image: docker.pkg.github.com/syafiqtermizi/questionbank-storage/qbankstorage:latest
    command: poetry run gunicorn converter:app --bind 0:80
    env_file:
      - ../.env

  question_doc_server:
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - question_doc_converter
